#Lateral distance off the front most marker, positive is left negative is right
float32 lateralDistanceFromFrontMarker
#Distance to end of front most marker, -1 if can't see end
float32 distanceFromEndOfFrontMarker
#Deviation angle from parallel of front most marker
float32 angleToParallelFrontMarker
#Lateral distance off of rear marker, positive is left negative is right
float32 lateralDistanceFromRearMarker
#Distance to end of rear marker, -1 if can't see end
float32 distanceFromEndRearMarker
#Deviation angle from parallel of rear marker
float32 angleToParallelRearMarker


